name: frameit_chrome
version: 1.0.0
description: >-
  Embed app store and play store screenshots in device frames.
  Drop in replacement for fastlane frameit.
homepage: https://github.com/melodysdreamj/frameit-chrome

executables:
  frameit_chrome: frameit_chrome

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  meta: '>=1.0.0 <2.0.0'
  args: ^2.3.1
  yaml: ^3.1.1
  logging: ^1.1.0
  logging_appenders: ^1.0.0
  image: ^3.2.2
  # (Small) utility packages
  quiver: ^3.1.0
  path: ^1.7.0
  json_annotation: ^4.5.0
  archive: ^3.3.0
  supercharged_dart: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.2
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  builder_static_text: ^0.1.0
  source_gen: ^1.2.6
  build: ^2.3.1
  glob: ^2.1.1
  recase: ^3.0.0
