name: frameit_chrome
version: 1.0.0
description: >-
  Embed app store and play store screenshots in device frames.
  Drop in replacement for fastlane frameit.
homepage: https://github.com/authpass/frameit-chrome

executables:
  frameit_chrome: frameit_chrome

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta:
  args:
  yaml:
  logging:
  logging_appenders:
  image:
  # (Small) utility packages
  quiver:
  path:
  json_annotation:
  archive:
  supercharged_dart:

dev_dependencies:
  builder_static_text:
  source_gen:
  build:
  glob:
  recase:

  build_runner:
  json_serializable:
